#!../../bin/darwin-x86/pyepics

## You may have to change pyepics to something else
## everywhere it appears in this file

< envPaths

cd "${TOP}"

## Register all support components
dbLoadDatabase "dbd/pyepics.dbd"
pyepics_registerRecordDeviceDriver pdbbase

## Load record instances
dbLoadRecords("db/demo.db")
dbLoadRecords("db/val.db", "NUM=00")
dbLoadRecords("db/val.db", "NUM=01")
dbLoadRecords("db/val.db", "NUM=02")
dbLoadRecords("db/val.db", "NUM=03")
dbLoadRecords("db/val.db", "NUM=04")
dbLoadRecords("db/val.db", "NUM=05")
dbLoadRecords("db/val.db", "NUM=06")
dbLoadRecords("db/val.db", "NUM=07")
dbLoadRecords("db/val.db", "NUM=08")
dbLoadRecords("db/val.db", "NUM=09")
dbLoadRecords("db/val.db", "NUM=10")
dbLoadRecords("db/val.db", "NUM=11")
dbLoadRecords("db/val.db", "NUM=12")
dbLoadRecords("db/val.db", "NUM=13")
dbLoadRecords("db/val.db", "NUM=14")
dbLoadRecords("db/val.db", "NUM=15")
dbLoadRecords("db/val.db", "NUM=16")
dbLoadRecords("db/val.db", "NUM=17")
dbLoadRecords("db/val.db", "NUM=18")
dbLoadRecords("db/val.db", "NUM=19")
dbLoadRecords("db/val.db", "NUM=20")
dbLoadRecords("db/val.db", "NUM=21")
dbLoadRecords("db/val.db", "NUM=22")
dbLoadRecords("db/val.db", "NUM=23")
dbLoadRecords("db/val.db", "NUM=24")
dbLoadRecords("db/val.db", "NUM=25")
dbLoadRecords("db/val.db", "NUM=26")
dbLoadRecords("db/val.db", "NUM=27")
dbLoadRecords("db/val.db", "NUM=28")
dbLoadRecords("db/val.db", "NUM=29")
dbLoadRecords("db/val.db", "NUM=30")
dbLoadRecords("db/val.db", "NUM=31")
dbLoadRecords("db/val.db", "NUM=32")
dbLoadRecords("db/val.db", "NUM=33")
dbLoadRecords("db/val.db", "NUM=34")
dbLoadRecords("db/val.db", "NUM=35")
dbLoadRecords("db/val.db", "NUM=36")
dbLoadRecords("db/val.db", "NUM=37")
dbLoadRecords("db/val.db", "NUM=38")
dbLoadRecords("db/val.db", "NUM=39")
dbLoadRecords("db/val.db", "NUM=40")
dbLoadRecords("db/val.db", "NUM=41")
dbLoadRecords("db/val.db", "NUM=42")
dbLoadRecords("db/val.db", "NUM=43")
dbLoadRecords("db/val.db", "NUM=44")
dbLoadRecords("db/val.db", "NUM=45")
dbLoadRecords("db/val.db", "NUM=46")
dbLoadRecords("db/val.db", "NUM=47")
dbLoadRecords("db/val.db", "NUM=48")
dbLoadRecords("db/val.db", "NUM=49")
dbLoadRecords("db/val.db", "NUM=50")
dbLoadRecords("db/val.db", "NUM=51")
dbLoadRecords("db/val.db", "NUM=52")
dbLoadRecords("db/val.db", "NUM=53")
dbLoadRecords("db/val.db", "NUM=54")
dbLoadRecords("db/val.db", "NUM=55")
dbLoadRecords("db/val.db", "NUM=56")
dbLoadRecords("db/val.db", "NUM=57")
dbLoadRecords("db/val.db", "NUM=58")
dbLoadRecords("db/val.db", "NUM=59")
dbLoadRecords("db/val.db", "NUM=60")
dbLoadRecords("db/val.db", "NUM=61")
dbLoadRecords("db/val.db", "NUM=62")
dbLoadRecords("db/val.db", "NUM=63")
dbLoadRecords("db/val.db", "NUM=64")
dbLoadRecords("db/val.db", "NUM=65")
dbLoadRecords("db/val.db", "NUM=66")
dbLoadRecords("db/val.db", "NUM=67")
dbLoadRecords("db/val.db", "NUM=68")
dbLoadRecords("db/val.db", "NUM=69")
dbLoadRecords("db/val.db", "NUM=70")
dbLoadRecords("db/val.db", "NUM=71")
dbLoadRecords("db/val.db", "NUM=72")
dbLoadRecords("db/val.db", "NUM=73")
dbLoadRecords("db/val.db", "NUM=74")
dbLoadRecords("db/val.db", "NUM=75")
dbLoadRecords("db/val.db", "NUM=76")
dbLoadRecords("db/val.db", "NUM=77")
dbLoadRecords("db/val.db", "NUM=78")
dbLoadRecords("db/val.db", "NUM=79")
dbLoadRecords("db/val.db", "NUM=80")
dbLoadRecords("db/val.db", "NUM=81")
dbLoadRecords("db/val.db", "NUM=82")
dbLoadRecords("db/val.db", "NUM=83")
dbLoadRecords("db/val.db", "NUM=84")
dbLoadRecords("db/val.db", "NUM=85")
dbLoadRecords("db/val.db", "NUM=86")
dbLoadRecords("db/val.db", "NUM=87")
dbLoadRecords("db/val.db", "NUM=88")
dbLoadRecords("db/val.db", "NUM=89")
dbLoadRecords("db/val.db", "NUM=90")
dbLoadRecords("db/val.db", "NUM=91")
dbLoadRecords("db/val.db", "NUM=92")
dbLoadRecords("db/val.db", "NUM=93")
dbLoadRecords("db/val.db", "NUM=94")
dbLoadRecords("db/val.db", "NUM=95")
dbLoadRecords("db/val.db", "NUM=96")
dbLoadRecords("db/val.db", "NUM=97")
dbLoadRecords("db/val.db", "NUM=98")
dbLoadRecords("db/val.db", "NUM=99")

cd "${TOP}/iocBoot/${IOC}"
iocInit

## Start any sequence programs
#seq sncxxx,"user=robbieHost"
